# Generated by Django 6.0.5 on 2026-06-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True),
        ),
    ]
